name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      working-directory: ./zadanie9/backend
      env: 
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      working-directory: ./zadanie9/backend
      run: docker build . --file Dockerfile --tag lmaruszak/server:latest
    - name: Docker Push
      working-directory: ./zadanie9/backend
      run: docker push lmaruszak/server:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'the-gadget-zone-server'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b8a7322895024647b13baae9cd597886 }}
        images: 'lmaruszak/server:latest'
