# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - the-gadget-zone-server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_e7b991c212f5488da1c03ac4e43c4aca }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f24def58791346818c4a2a9a10d0a3e5 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e7b991c212f5488da1c03ac4e43c4aca }}/lmaruszak/server:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'the-gadget-zone-server'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b8a7322895024647b13baae9cd597886 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e7b991c212f5488da1c03ac4e43c4aca }}/lmaruszak/server:${{ github.sha }}'